In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
initial_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
initial_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME' 'STATUS', 'SPECIAL_CONSIDERATIONS'.
initial_df = initial_df.drop(columns = ['EIN', 'NAME', 'STATUS', 'SPECIAL_CONSIDERATIONS'])
initial_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1
...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,5000,0
34297,T5,Independent,C3000,ProductDev,Association,0,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,36500179,0

In [4]:
# Determine the number of unique values in each column.
initial_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [5]:
# Drop the non-beneficial ID columns, 'ASK_AMT	'.
initial_df = initial_df.drop(columns = ['ASK_AMT'])
initial_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,1
...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,0
34297,T5,Independent,C3000,ProductDev,Association,0,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,0

In [6]:
# Determine the number of unique values in each column.
initial_df.nunique()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
INCOME_AMT           9
IS_SUCCESSFUL        2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
type_counts = initial_df['APPLICATION_TYPE'].value_counts()
type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(type_counts.iloc[8:].index)
cutoff_value = 725

# Replace in dataframe
for app in application_types_to_replace:
    initial_df['APPLICATION_TYPE'] = initial_df['APPLICATION_TYPE'].replace(app,"Other_app_type")

# Check to make sure binning was successful
initial_df['APPLICATION_TYPE'].value_counts()

T3                27037
T4                 1542
T6                 1216
T5                 1173
T19                1065
T8                  737
T7                  725
T10                 528
Other_app_type      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
classification_types = initial_df['CLASSIFICATION'].value_counts()
classification_types

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_types.iloc[5:].index)
cutoff_value_classifications = 1918

# Replace in dataframe
for cls in classifications_to_replace:
    initial_df['CLASSIFICATION'] = initial_df['CLASSIFICATION'].replace(cls,"Other_classification")
    
# Check to make sure binning was successful
initial_df['CLASSIFICATION'].value_counts()

C1000                   17326
C2000                    6074
C1200                    4837
Other_classification     2261
C3000                    1918
C2100                    1883
Name: CLASSIFICATION, dtype: int64

In [11]:
#convert the categorical data in numeric using get_dummies()
dummies = pd.get_dummies(initial_df)
dummies.head()

,IS_SUCCESSFUL,APPLICATION_TYPE_Other_app_type,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,0,0,0,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,1,0,0,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [12]:
# Split our preprocessed data into our features and target arrays
y = dummies['IS_SUCCESSFUL'].values
X = dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [14]:
# (FIRST ATTEMPT - ACCURACY 72%)
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 320

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 371 (1.45 KB)
Trainable params: 371 (1.45 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model (FIRST ATTEMPT)
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Train the model (FIRST ATTEMPT)
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 425us/step - loss: 0.6538 - accuracy: 0.6591
Epoch 2/100
804/804 [==============================] - 0s 418us/step - loss: 0.5692 - accuracy: 0.7229
Epoch 3/100
804/804 [==============================] - 0s 406us/step - loss: 0.5619 - accuracy: 0.7261
Epoch 4/100
804/804 [==============================] - 0s 407us/step - loss: 0.5591 - accuracy: 0.7276
Epoch 5/100
804/804 [==============================] - 0s 405us/step - loss: 0.5571 - accuracy: 0.7280
Epoch 6/100
804/804 [==============================] - 0s 408us/step - loss: 0.5558 - accuracy: 0.7282
Epoch 7/100
804/804 [==============================] - 0s 414us/step - loss: 0.5549 - accuracy: 0.7298
Epoch 8/100
804/804 [==============================] - 0s 407us/step - loss: 0.5539 - accuracy: 0.7298
Epoch 9/100
804/804 [==============================] - 0s 410us/step - loss: 0.5529 - accuracy: 0.7296
Epoch 10/100
804/804 [==============================] - 0s 405us/step - loss: 0.5529 - accuracy: 0.7300
Epoch 11/100
804/804 [==============================] - 0s 409us/step - loss: 0.5523 - accuracy: 0.7305
Epoch 12/100
804/804 [==============================] - 0s 408us/step - loss: 0.5517 - accuracy: 0.7314
Epoch 13/100
804/804 [==============================] - 0s 407us/step - loss: 0.5512 - accuracy: 0.7306
Epoch 14/100
804/804 [==============================] - 0s 408us/step - loss: 0.5510 - accuracy: 0.7308
Epoch 15/100
804/804 [==============================] - 0s 406us/step - loss: 0.5505 - accuracy: 0.7313
Epoch 16/100
804/804 [==============================] - 0s 455us/step - loss: 0.5504 - accuracy: 0.7310
Epoch 17/100
804/804 [==============================] - 0s 441us/step - loss: 0.5499 - accuracy: 0.7310
Epoch 18/100
804/804 [==============================] - 0s 429us/step - loss: 0.5496 - accuracy: 0.7313
Epoch 19/100
804/804 [==============================] - 0s 423us/step - loss: 0.5493 - accuracy: 0.7318
Epoch 20/100
804/804 [==============================] - 0s 410us/step - loss: 0.5490 - accuracy: 0.7322
Epoch 21/100
804/804 [==============================] - 0s 411us/step - loss: 0.5487 - accuracy: 0.7312
Epoch 22/100
804/804 [==============================] - 0s 408us/step - loss: 0.5484 - accuracy: 0.7327
Epoch 23/100
804/804 [==============================] - 0s 419us/step - loss: 0.5484 - accuracy: 0.7317
Epoch 24/100
804/804 [==============================] - 0s 409us/step - loss: 0.5478 - accuracy: 0.7324
Epoch 25/100
804/804 [==============================] - 0s 407us/step - loss: 0.5476 - accuracy: 0.7324
Epoch 26/100
804/804 [==============================] - 0s 408us/step - loss: 0.5478 - accuracy: 0.7321
Epoch 27/100
804/804 [==============================] - 0s 408us/step - loss: 0.5473 - accuracy: 0.7322
Epoch 28/100
804/804 [==============================] - 0s 408us/step - loss: 0.5471 - accuracy: 0.7324
Epoch 29/100
804/804 [==============================] - 0s 411us/step - loss: 0.5470 - accuracy: 0.7326
Epoch 30/100
804/804 [==============================] - 0s 407us/step - loss: 0.5468 - accuracy: 0.7315
Epoch 31/100
804/804 [==============================] - 0s 413us/step - loss: 0.5468 - accuracy: 0.7325
Epoch 32/100
804/804 [==============================] - 0s 408us/step - loss: 0.5467 - accuracy: 0.7332
Epoch 33/100
804/804 [==============================] - 0s 402us/step - loss: 0.5467 - accuracy: 0.7329
Epoch 34/100
804/804 [==============================] - 0s 404us/step - loss: 0.5467 - accuracy: 0.7327
Epoch 35/100
804/804 [==============================] - 0s 439us/step - loss: 0.5464 - accuracy: 0.7321
Epoch 36/100
804/804 [==============================] - 0s 403us/step - loss: 0.5463 - accuracy: 0.7328
Epoch 37/100
804/804 [==============================] - 0s 400us/step - loss: 0.5458 - accuracy: 0.7334
Epoch 38/100
804/804 [==============================] - 0s 402us/step - loss: 0.5462 - accuracy: 0.7323
Epoch 39/100
804/804 [==============================] - 0s 404us/step - loss: 0.5458 - accuracy: 0.7331
Epoch 40/100
804/804 [==============================] - 0s 412us/step - loss: 0.5462 - accuracy: 0.7330
Epoch 41/100
804/804 [==============================] - 0s 403us/step - loss: 0.5459 - accuracy: 0.7331
Epoch 42/100
804/804 [==============================] - 0s 402us/step - loss: 0.5455 - accuracy: 0.7340
Epoch 43/100
804/804 [==============================] - 0s 403us/step - loss: 0.5457 - accuracy: 0.7331
Epoch 44/100
804/804 [==============================] - 0s 403us/step - loss: 0.5456 - accuracy: 0.7337
Epoch 45/100
804/804 [==============================] - 0s 402us/step - loss: 0.5457 - accuracy: 0.7338
Epoch 46/100
804/804 [==============================] - 0s 408us/step - loss: 0.5454 - accuracy: 0.7324
Epoch 47/100
804/804 [==============================] - 0s 402us/step - loss: 0.5454 - accuracy: 0.7331
Epoch 48/100
804/804 [==============================] - 0s 402us/step - loss: 0.5452 - accuracy: 0.7334
Epoch 49/100
804/804 [==============================] - 0s 404us/step - loss: 0.5453 - accuracy: 0.7327
Epoch 50/100
804/804 [==============================] - 0s 402us/step - loss: 0.5454 - accuracy: 0.7336
Epoch 51/100
804/804 [==============================] - 0s 401us/step - loss: 0.5452 - accuracy: 0.7339
Epoch 52/100
804/804 [==============================] - 0s 402us/step - loss: 0.5450 - accuracy: 0.7338
Epoch 53/100
804/804 [==============================] - 0s 437us/step - loss: 0.5449 - accuracy: 0.7341
Epoch 54/100
804/804 [==============================] - 0s 403us/step - loss: 0.5451 - accuracy: 0.7327
Epoch 55/100
804/804 [==============================] - 0s 404us/step - loss: 0.5451 - accuracy: 0.7336
Epoch 56/100
804/804 [==============================] - 0s 403us/step - loss: 0.5446 - accuracy: 0.7341
Epoch 57/100
804/804 [==============================] - 0s 410us/step - loss: 0.5448 - accuracy: 0.7338
Epoch 58/100
804/804 [==============================] - 0s 405us/step - loss: 0.5446 - accuracy: 0.7348
Epoch 59/100
804/804 [==============================] - 0s 405us/step - loss: 0.5448 - accuracy: 0.7341
Epoch 60/100
804/804 [==============================] - 0s 401us/step - loss: 0.5447 - accuracy: 0.7344
Epoch 61/100
804/804 [==============================] - 0s 404us/step - loss: 0.5446 - accuracy: 0.7342
Epoch 62/100
804/804 [==============================] - 0s 402us/step - loss: 0.5447 - accuracy: 0.7340
Epoch 63/100
804/804 [==============================] - 0s 407us/step - loss: 0.5444 - accuracy: 0.7339
Epoch 64/100
804/804 [==============================] - 0s 401us/step - loss: 0.5443 - accuracy: 0.7343
Epoch 65/100
804/804 [==============================] - 0s 403us/step - loss: 0.5446 - accuracy: 0.7345
Epoch 66/100
804/804 [==============================] - 0s 404us/step - loss: 0.5447 - accuracy: 0.7337
Epoch 67/100
804/804 [==============================] - 0s 400us/step - loss: 0.5440 - accuracy: 0.7344
Epoch 68/100
804/804 [==============================] - 0s 402us/step - loss: 0.5444 - accuracy: 0.7332
Epoch 69/100
804/804 [==============================] - 0s 437us/step - loss: 0.5444 - accuracy: 0.7343
Epoch 70/100
804/804 [==============================] - 0s 406us/step - loss: 0.5443 - accuracy: 0.7343
Epoch 71/100
804/804 [==============================] - 0s 402us/step - loss: 0.5443 - accuracy: 0.7350
Epoch 72/100
804/804 [==============================] - 0s 403us/step - loss: 0.5442 - accuracy: 0.7350
Epoch 73/100
804/804 [==============================] - 0s 405us/step - loss: 0.5443 - accuracy: 0.7346
Epoch 74/100
804/804 [==============================] - 0s 411us/step - loss: 0.5443 - accuracy: 0.7335
Epoch 75/100
804/804 [==============================] - 0s 417us/step - loss: 0.5444 - accuracy: 0.7340
Epoch 76/100
804/804 [==============================] - 0s 403us/step - loss: 0.5442 - accuracy: 0.7339
Epoch 77/100
804/804 [==============================] - 0s 402us/step - loss: 0.5438 - accuracy: 0.7350
Epoch 78/100
804/804 [==============================] - 0s 402us/step - loss: 0.5440 - accuracy: 0.7336
Epoch 79/100
804/804 [==============================] - 0s 450us/step - loss: 0.5437 - accuracy: 0.7346
Epoch 80/100
804/804 [==============================] - 0s 406us/step - loss: 0.5434 - accuracy: 0.7347
Epoch 81/100
804/804 [==============================] - 0s 403us/step - loss: 0.5437 - accuracy: 0.7348
Epoch 82/100
804/804 [==============================] - 0s 404us/step - loss: 0.5437 - accuracy: 0.7345
Epoch 83/100
804/804 [==============================] - 0s 403us/step - loss: 0.5438 - accuracy: 0.7344
Epoch 84/100
804/804 [==============================] - 0s 401us/step - loss: 0.5436 - accuracy: 0.7346
Epoch 85/100
804/804 [==============================] - 0s 403us/step - loss: 0.5437 - accuracy: 0.7340
Epoch 86/100
804/804 [==============================] - 0s 411us/step - loss: 0.5435 - accuracy: 0.7344
Epoch 87/100
804/804 [==============================] - 0s 404us/step - loss: 0.5438 - accuracy: 0.7339
Epoch 88/100
804/804 [==============================] - 0s 404us/step - loss: 0.5437 - accuracy: 0.7336
Epoch 89/100
804/804 [==============================] - 0s 400us/step - loss: 0.5436 - accuracy: 0.7343
Epoch 90/100
804/804 [==============================] - 0s 404us/step - loss: 0.5434 - accuracy: 0.7345
Epoch 91/100
804/804 [==============================] - 0s 408us/step - loss: 0.5432 - accuracy: 0.7347
Epoch 92/100
804/804 [==============================] - 0s 408us/step - loss: 0.5437 - accuracy: 0.7338
Epoch 93/100
804/804 [==============================] - 0s 402us/step - loss: 0.5435 - accuracy: 0.7340
Epoch 94/100
804/804 [==============================] - 0s 435us/step - loss: 0.5435 - accuracy: 0.7338
Epoch 95/100
804/804 [==============================] - 0s 402us/step - loss: 0.5435 - accuracy: 0.7341
Epoch 96/100
804/804 [==============================] - 0s 403us/step - loss: 0.5435 - accuracy: 0.7343
Epoch 97/100
804/804 [==============================] - 0s 406us/step - loss: 0.5434 - accuracy: 0.7345
Epoch 98/100
804/804 [==============================] - 0s 403us/step - loss: 0.5435 - accuracy: 0.7336
Epoch 99/100
804/804 [==============================] - 0s 403us/step - loss: 0.5434 - accuracy: 0.7346
Epoch 100/100
804/804 [==============================] - 0s 398us/step - loss: 0.5434 - accuracy: 0.7341

In [17]:
# Evaluate the model using the test data (FIRST ATTEMPT)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5518 - accuracy: 0.7286 - 156ms/epoch - 581us/step
Loss: 0.5517749786376953, Accuracy: 0.7286297082901001

In [18]:
# (SECOND ATTEMPT - ACCURACY 72%)
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 10)                400

 dense_4 (Dense)             (None, 10)                110

 dense_5 (Dense)             (None, 1)                 11

=================================================================
Total params: 521 (2.04 KB)
Trainable params: 521 (2.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
# Compile the model (SECOND ATTEMPT)
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [20]:
# Train the model (SECOND ATTEMPT)
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 508us/step - loss: 0.6005 - accuracy: 0.6949
Epoch 2/100
804/804 [==============================] - 0s 572us/step - loss: 0.5671 - accuracy: 0.7240
Epoch 3/100
804/804 [==============================] - 0s 449us/step - loss: 0.5602 - accuracy: 0.7254
Epoch 4/100
804/804 [==============================] - 0s 422us/step - loss: 0.5576 - accuracy: 0.7273
Epoch 5/100
804/804 [==============================] - 0s 425us/step - loss: 0.5552 - accuracy: 0.7278
Epoch 6/100
804/804 [==============================] - 0s 421us/step - loss: 0.5536 - accuracy: 0.7278
Epoch 7/100
804/804 [==============================] - 0s 414us/step - loss: 0.5525 - accuracy: 0.7283
Epoch 8/100
804/804 [==============================] - 0s 415us/step - loss: 0.5518 - accuracy: 0.7283
Epoch 9/100
804/804 [==============================] - 0s 416us/step - loss: 0.5508 - accuracy: 0.7293
Epoch 10/100
804/804 [==============================] - 0s 426us/step - loss: 0.5500 - accuracy: 0.7299
Epoch 11/100
804/804 [==============================] - 0s 430us/step - loss: 0.5495 - accuracy: 0.7295
Epoch 12/100
804/804 [==============================] - 0s 414us/step - loss: 0.5494 - accuracy: 0.7300
Epoch 13/100
804/804 [==============================] - 0s 412us/step - loss: 0.5488 - accuracy: 0.7290
Epoch 14/100
804/804 [==============================] - 0s 416us/step - loss: 0.5482 - accuracy: 0.7307
Epoch 15/100
804/804 [==============================] - 0s 428us/step - loss: 0.5479 - accuracy: 0.7309
Epoch 16/100
804/804 [==============================] - 0s 416us/step - loss: 0.5478 - accuracy: 0.7304
Epoch 17/100
804/804 [==============================] - 0s 415us/step - loss: 0.5477 - accuracy: 0.7310
Epoch 18/100
804/804 [==============================] - 0s 414us/step - loss: 0.5475 - accuracy: 0.7307
Epoch 19/100
804/804 [==============================] - 0s 422us/step - loss: 0.5469 - accuracy: 0.7316
Epoch 20/100
804/804 [==============================] - 0s 452us/step - loss: 0.5470 - accuracy: 0.7310
Epoch 21/100
804/804 [==============================] - 0s 415us/step - loss: 0.5468 - accuracy: 0.7321
Epoch 22/100
804/804 [==============================] - 0s 413us/step - loss: 0.5467 - accuracy: 0.7322
Epoch 23/100
804/804 [==============================] - 0s 411us/step - loss: 0.5464 - accuracy: 0.7323
Epoch 24/100
804/804 [==============================] - 0s 414us/step - loss: 0.5461 - accuracy: 0.7316
Epoch 25/100
804/804 [==============================] - 0s 410us/step - loss: 0.5463 - accuracy: 0.7315
Epoch 26/100
804/804 [==============================] - 0s 413us/step - loss: 0.5458 - accuracy: 0.7308
Epoch 27/100
804/804 [==============================] - 0s 414us/step - loss: 0.5458 - accuracy: 0.7321
Epoch 28/100
804/804 [==============================] - 0s 414us/step - loss: 0.5460 - accuracy: 0.7309
Epoch 29/100
804/804 [==============================] - 0s 414us/step - loss: 0.5455 - accuracy: 0.7315
Epoch 30/100
804/804 [==============================] - 0s 413us/step - loss: 0.5456 - accuracy: 0.7320
Epoch 31/100
804/804 [==============================] - 0s 414us/step - loss: 0.5454 - accuracy: 0.7315
Epoch 32/100
804/804 [==============================] - 0s 414us/step - loss: 0.5452 - accuracy: 0.7324
Epoch 33/100
804/804 [==============================] - 0s 426us/step - loss: 0.5452 - accuracy: 0.7337
Epoch 34/100
804/804 [==============================] - 0s 422us/step - loss: 0.5450 - accuracy: 0.7321
Epoch 35/100
804/804 [==============================] - 0s 414us/step - loss: 0.5449 - accuracy: 0.7327
Epoch 36/100
804/804 [==============================] - 0s 415us/step - loss: 0.5449 - accuracy: 0.7330
Epoch 37/100
804/804 [==============================] - 0s 416us/step - loss: 0.5448 - accuracy: 0.7323
Epoch 38/100
804/804 [==============================] - 0s 415us/step - loss: 0.5446 - accuracy: 0.7322
Epoch 39/100
804/804 [==============================] - 0s 451us/step - loss: 0.5445 - accuracy: 0.7320
Epoch 40/100
804/804 [==============================] - 0s 414us/step - loss: 0.5444 - accuracy: 0.7329
Epoch 41/100
804/804 [==============================] - 0s 412us/step - loss: 0.5443 - accuracy: 0.7345
Epoch 42/100
804/804 [==============================] - 0s 415us/step - loss: 0.5442 - accuracy: 0.7325
Epoch 43/100
804/804 [==============================] - 0s 412us/step - loss: 0.5442 - accuracy: 0.7321
Epoch 44/100
804/804 [==============================] - 0s 414us/step - loss: 0.5442 - accuracy: 0.7338
Epoch 45/100
804/804 [==============================] - 0s 416us/step - loss: 0.5444 - accuracy: 0.7326
Epoch 46/100
804/804 [==============================] - 0s 413us/step - loss: 0.5442 - accuracy: 0.7336
Epoch 47/100
804/804 [==============================] - 0s 416us/step - loss: 0.5441 - accuracy: 0.7331
Epoch 48/100
804/804 [==============================] - 0s 420us/step - loss: 0.5437 - accuracy: 0.7332
Epoch 49/100
804/804 [==============================] - 0s 415us/step - loss: 0.5438 - accuracy: 0.7332
Epoch 50/100
804/804 [==============================] - 0s 412us/step - loss: 0.5438 - accuracy: 0.7339
Epoch 51/100
804/804 [==============================] - 0s 414us/step - loss: 0.5438 - accuracy: 0.7325
Epoch 52/100
804/804 [==============================] - 0s 413us/step - loss: 0.5438 - accuracy: 0.7336
Epoch 53/100
804/804 [==============================] - 0s 413us/step - loss: 0.5436 - accuracy: 0.7345
Epoch 54/100
804/804 [==============================] - 0s 426us/step - loss: 0.5433 - accuracy: 0.7333
Epoch 55/100
804/804 [==============================] - 0s 417us/step - loss: 0.5438 - accuracy: 0.7339
Epoch 56/100
804/804 [==============================] - 0s 429us/step - loss: 0.5432 - accuracy: 0.7339
Epoch 57/100
804/804 [==============================] - 0s 423us/step - loss: 0.5433 - accuracy: 0.7344
Epoch 58/100
804/804 [==============================] - 0s 415us/step - loss: 0.5435 - accuracy: 0.7339
Epoch 59/100
804/804 [==============================] - 0s 414us/step - loss: 0.5431 - accuracy: 0.7338
Epoch 60/100
804/804 [==============================] - 0s 422us/step - loss: 0.5432 - accuracy: 0.7351
Epoch 61/100
804/804 [==============================] - 0s 416us/step - loss: 0.5431 - accuracy: 0.7340
Epoch 62/100
804/804 [==============================] - 0s 412us/step - loss: 0.5429 - accuracy: 0.7343
Epoch 63/100
804/804 [==============================] - 0s 414us/step - loss: 0.5430 - accuracy: 0.7353
Epoch 64/100
804/804 [==============================] - 0s 412us/step - loss: 0.5425 - accuracy: 0.7345
Epoch 65/100
804/804 [==============================] - 0s 415us/step - loss: 0.5430 - accuracy: 0.7346
Epoch 66/100
804/804 [==============================] - 0s 414us/step - loss: 0.5430 - accuracy: 0.7336
Epoch 67/100
804/804 [==============================] - 0s 413us/step - loss: 0.5429 - accuracy: 0.7343
Epoch 68/100
804/804 [==============================] - 0s 413us/step - loss: 0.5429 - accuracy: 0.7356
Epoch 69/100
804/804 [==============================] - 0s 413us/step - loss: 0.5427 - accuracy: 0.7347
Epoch 70/100
804/804 [==============================] - 0s 414us/step - loss: 0.5430 - accuracy: 0.7339
Epoch 71/100
804/804 [==============================] - 0s 413us/step - loss: 0.5428 - accuracy: 0.7345
Epoch 72/100
804/804 [==============================] - 0s 413us/step - loss: 0.5427 - accuracy: 0.7349
Epoch 73/100
804/804 [==============================] - 0s 448us/step - loss: 0.5426 - accuracy: 0.7345
Epoch 74/100
804/804 [==============================] - 0s 415us/step - loss: 0.5425 - accuracy: 0.7342
Epoch 75/100
804/804 [==============================] - 0s 414us/step - loss: 0.5426 - accuracy: 0.7332
Epoch 76/100
804/804 [==============================] - 0s 424us/step - loss: 0.5425 - accuracy: 0.7345
Epoch 77/100
804/804 [==============================] - 0s 413us/step - loss: 0.5427 - accuracy: 0.7347
Epoch 78/100
804/804 [==============================] - 0s 413us/step - loss: 0.5423 - accuracy: 0.7339
Epoch 79/100
804/804 [==============================] - 0s 415us/step - loss: 0.5424 - accuracy: 0.7335
Epoch 80/100
804/804 [==============================] - 0s 413us/step - loss: 0.5424 - accuracy: 0.7343
Epoch 81/100
804/804 [==============================] - 0s 411us/step - loss: 0.5423 - accuracy: 0.7349
Epoch 82/100
804/804 [==============================] - 0s 410us/step - loss: 0.5424 - accuracy: 0.7341
Epoch 83/100
804/804 [==============================] - 0s 412us/step - loss: 0.5420 - accuracy: 0.7348
Epoch 84/100
804/804 [==============================] - 0s 413us/step - loss: 0.5422 - accuracy: 0.7347
Epoch 85/100
804/804 [==============================] - 0s 415us/step - loss: 0.5423 - accuracy: 0.7341
Epoch 86/100
804/804 [==============================] - 0s 414us/step - loss: 0.5421 - accuracy: 0.7348
Epoch 87/100
804/804 [==============================] - 0s 448us/step - loss: 0.5421 - accuracy: 0.7355
Epoch 88/100
804/804 [==============================] - 0s 411us/step - loss: 0.5424 - accuracy: 0.7350
Epoch 89/100
804/804 [==============================] - 0s 414us/step - loss: 0.5424 - accuracy: 0.7351
Epoch 90/100
804/804 [==============================] - 0s 414us/step - loss: 0.5422 - accuracy: 0.7348
Epoch 91/100
804/804 [==============================] - 0s 414us/step - loss: 0.5422 - accuracy: 0.7354
Epoch 92/100
804/804 [==============================] - 0s 420us/step - loss: 0.5423 - accuracy: 0.7361
Epoch 93/100
804/804 [==============================] - 0s 416us/step - loss: 0.5423 - accuracy: 0.7342
Epoch 94/100
804/804 [==============================] - 0s 414us/step - loss: 0.5424 - accuracy: 0.7343
Epoch 95/100
804/804 [==============================] - 0s 424us/step - loss: 0.5418 - accuracy: 0.7345
Epoch 96/100
804/804 [==============================] - 0s 411us/step - loss: 0.5421 - accuracy: 0.7353
Epoch 97/100
804/804 [==============================] - 0s 413us/step - loss: 0.5421 - accuracy: 0.7354
Epoch 98/100
804/804 [==============================] - 0s 413us/step - loss: 0.5423 - accuracy: 0.7339
Epoch 99/100
804/804 [==============================] - 0s 413us/step - loss: 0.5417 - accuracy: 0.7362
Epoch 100/100
804/804 [==============================] - 0s 416us/step - loss: 0.5418 - accuracy: 0.7352

In [21]:
# Evaluate the model using the test data (SECOND ATTEMPT)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5520 - accuracy: 0.7307 - 151ms/epoch - 563us/step
Loss: 0.5519621968269348, Accuracy: 0.7307288646697998

In [22]:
# (THIRD ATTEMPT - ACCURACY 72%)
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 20
hidden_nodes_layer2 = 20

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "tanh"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="relu"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 20)                800

 dense_7 (Dense)             (None, 20)                420

 dense_8 (Dense)             (None, 1)                 21

=================================================================
Total params: 1241 (4.85 KB)
Trainable params: 1241 (4.85 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [23]:
# Compile the model (THIRD ATTEMPT)
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
# Train the model (THIRD ATTEMPT)
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 503us/step - loss: 0.7235 - accuracy: 0.6612
Epoch 2/100
804/804 [==============================] - 0s 476us/step - loss: 0.5741 - accuracy: 0.7194
Epoch 3/100
804/804 [==============================] - 0s 480us/step - loss: 0.5672 - accuracy: 0.7226
Epoch 4/100
804/804 [==============================] - 0s 459us/step - loss: 0.5878 - accuracy: 0.7080
Epoch 5/100
804/804 [==============================] - 0s 472us/step - loss: 0.5649 - accuracy: 0.7266
Epoch 6/100
804/804 [==============================] - 0s 442us/step - loss: 0.5580 - accuracy: 0.7275
Epoch 7/100
804/804 [==============================] - 0s 436us/step - loss: 0.5559 - accuracy: 0.7294
Epoch 8/100
804/804 [==============================] - 0s 435us/step - loss: 0.6214 - accuracy: 0.7098
Epoch 9/100
804/804 [==============================] - 0s 435us/step - loss: 0.5791 - accuracy: 0.7157
Epoch 10/100
804/804 [==============================] - 0s 437us/step - loss: 0.5621 - accuracy: 0.7287
Epoch 11/100
804/804 [==============================] - 0s 436us/step - loss: 0.5570 - accuracy: 0.7290
Epoch 12/100
804/804 [==============================] - 0s 434us/step - loss: 0.5544 - accuracy: 0.7302
Epoch 13/100
804/804 [==============================] - 0s 436us/step - loss: 0.5531 - accuracy: 0.7294
Epoch 14/100
804/804 [==============================] - 0s 433us/step - loss: 0.5527 - accuracy: 0.7295
Epoch 15/100
804/804 [==============================] - 0s 437us/step - loss: 0.5603 - accuracy: 0.7264
Epoch 16/100
804/804 [==============================] - 0s 437us/step - loss: 0.5525 - accuracy: 0.7298
Epoch 17/100
804/804 [==============================] - 0s 463us/step - loss: 0.5550 - accuracy: 0.7287
Epoch 18/100
804/804 [==============================] - 0s 489us/step - loss: 0.5532 - accuracy: 0.7308
Epoch 19/100
804/804 [==============================] - 0s 450us/step - loss: 0.5510 - accuracy: 0.7303
Epoch 20/100
804/804 [==============================] - 0s 442us/step - loss: 0.5578 - accuracy: 0.7278
Epoch 21/100
804/804 [==============================] - 0s 468us/step - loss: 0.5570 - accuracy: 0.7287
Epoch 22/100
804/804 [==============================] - 0s 441us/step - loss: 0.5523 - accuracy: 0.7293
Epoch 23/100
804/804 [==============================] - 0s 453us/step - loss: 0.5518 - accuracy: 0.7307
Epoch 24/100
804/804 [==============================] - 0s 458us/step - loss: 0.5499 - accuracy: 0.7321
Epoch 25/100
804/804 [==============================] - 0s 493us/step - loss: 0.5548 - accuracy: 0.7275
Epoch 26/100
804/804 [==============================] - 0s 503us/step - loss: 0.5483 - accuracy: 0.7307
Epoch 27/100
804/804 [==============================] - 0s 481us/step - loss: 0.5502 - accuracy: 0.7305
Epoch 28/100
804/804 [==============================] - 0s 463us/step - loss: 0.5501 - accuracy: 0.7304
Epoch 29/100
804/804 [==============================] - 0s 442us/step - loss: 0.5479 - accuracy: 0.7311
Epoch 30/100
804/804 [==============================] - 0s 445us/step - loss: 0.5536 - accuracy: 0.7301
Epoch 31/100
804/804 [==============================] - 0s 446us/step - loss: 0.5676 - accuracy: 0.7180
Epoch 32/100
804/804 [==============================] - 0s 446us/step - loss: 0.5486 - accuracy: 0.7308
Epoch 33/100
804/804 [==============================] - 0s 483us/step - loss: 0.5477 - accuracy: 0.7305
Epoch 34/100
804/804 [==============================] - 0s 449us/step - loss: 0.5525 - accuracy: 0.7274
Epoch 35/100
804/804 [==============================] - 0s 449us/step - loss: 0.5489 - accuracy: 0.7306
Epoch 36/100
804/804 [==============================] - 0s 446us/step - loss: 0.5527 - accuracy: 0.7309
Epoch 37/100
804/804 [==============================] - 0s 443us/step - loss: 0.5471 - accuracy: 0.7321
Epoch 38/100
804/804 [==============================] - 0s 444us/step - loss: 0.5501 - accuracy: 0.7308
Epoch 39/100
804/804 [==============================] - 0s 444us/step - loss: 0.5615 - accuracy: 0.7270
Epoch 40/100
804/804 [==============================] - 0s 449us/step - loss: 0.5490 - accuracy: 0.7303
Epoch 41/100
804/804 [==============================] - 0s 444us/step - loss: 0.5470 - accuracy: 0.7326
Epoch 42/100
804/804 [==============================] - 0s 443us/step - loss: 0.5479 - accuracy: 0.7319
Epoch 43/100
804/804 [==============================] - 0s 443us/step - loss: 0.5472 - accuracy: 0.7317
Epoch 44/100
804/804 [==============================] - 0s 455us/step - loss: 0.5502 - accuracy: 0.7308
Epoch 45/100
804/804 [==============================] - 0s 446us/step - loss: 0.5493 - accuracy: 0.7318
Epoch 46/100
804/804 [==============================] - 0s 448us/step - loss: 0.5470 - accuracy: 0.7318
Epoch 47/100
804/804 [==============================] - 0s 444us/step - loss: 0.5465 - accuracy: 0.7317
Epoch 48/100
804/804 [==============================] - 0s 446us/step - loss: 0.5506 - accuracy: 0.7324
Epoch 49/100
804/804 [==============================] - 0s 445us/step - loss: 0.5732 - accuracy: 0.7231
Epoch 50/100
804/804 [==============================] - 0s 483us/step - loss: 0.5476 - accuracy: 0.7324
Epoch 51/100
804/804 [==============================] - 0s 445us/step - loss: 0.5464 - accuracy: 0.7338
Epoch 52/100
804/804 [==============================] - 0s 443us/step - loss: 0.5452 - accuracy: 0.7329
Epoch 53/100
804/804 [==============================] - 0s 445us/step - loss: 0.5491 - accuracy: 0.7308
Epoch 54/100
804/804 [==============================] - 0s 446us/step - loss: 0.5741 - accuracy: 0.7152
Epoch 55/100
804/804 [==============================] - 0s 445us/step - loss: 0.5478 - accuracy: 0.7331
Epoch 56/100
804/804 [==============================] - 0s 444us/step - loss: 0.5485 - accuracy: 0.7328
Epoch 57/100
804/804 [==============================] - 0s 444us/step - loss: 0.5448 - accuracy: 0.7326
Epoch 58/100
804/804 [==============================] - 0s 445us/step - loss: 0.5453 - accuracy: 0.7337
Epoch 59/100
804/804 [==============================] - 0s 446us/step - loss: 0.5493 - accuracy: 0.7317
Epoch 60/100
804/804 [==============================] - 0s 444us/step - loss: 0.5451 - accuracy: 0.7329
Epoch 61/100
804/804 [==============================] - 0s 446us/step - loss: 0.5469 - accuracy: 0.7336
Epoch 62/100
804/804 [==============================] - 0s 446us/step - loss: 0.5464 - accuracy: 0.7340
Epoch 63/100
804/804 [==============================] - 0s 444us/step - loss: 0.5476 - accuracy: 0.7330
Epoch 64/100
804/804 [==============================] - 0s 444us/step - loss: 0.5470 - accuracy: 0.7327
Epoch 65/100
804/804 [==============================] - 0s 452us/step - loss: 0.5491 - accuracy: 0.7325
Epoch 66/100
804/804 [==============================] - 0s 482us/step - loss: 0.5784 - accuracy: 0.7170
Epoch 67/100
804/804 [==============================] - 0s 445us/step - loss: 0.5476 - accuracy: 0.7334
Epoch 68/100
804/804 [==============================] - 0s 444us/step - loss: 0.5438 - accuracy: 0.7329
Epoch 69/100
804/804 [==============================] - 0s 445us/step - loss: 0.5432 - accuracy: 0.7335
Epoch 70/100
804/804 [==============================] - 0s 442us/step - loss: 0.5454 - accuracy: 0.7328
Epoch 71/100
804/804 [==============================] - 0s 442us/step - loss: 0.5508 - accuracy: 0.7301
Epoch 72/100
804/804 [==============================] - 0s 444us/step - loss: 0.5441 - accuracy: 0.7342
Epoch 73/100
804/804 [==============================] - 0s 443us/step - loss: 0.5478 - accuracy: 0.7341
Epoch 74/100
804/804 [==============================] - 0s 441us/step - loss: 0.5449 - accuracy: 0.7334
Epoch 75/100
804/804 [==============================] - 0s 443us/step - loss: 0.5454 - accuracy: 0.7334
Epoch 76/100
804/804 [==============================] - 0s 440us/step - loss: 0.5451 - accuracy: 0.7329
Epoch 77/100
804/804 [==============================] - 0s 443us/step - loss: 0.5453 - accuracy: 0.7340
Epoch 78/100
804/804 [==============================] - 0s 441us/step - loss: 0.5455 - accuracy: 0.7332
Epoch 79/100
804/804 [==============================] - 0s 440us/step - loss: 0.5443 - accuracy: 0.7342
Epoch 80/100
804/804 [==============================] - 0s 474us/step - loss: 0.5510 - accuracy: 0.7325
Epoch 81/100
804/804 [==============================] - 0s 443us/step - loss: 0.5785 - accuracy: 0.7156
Epoch 82/100
804/804 [==============================] - 0s 440us/step - loss: 0.5476 - accuracy: 0.7345
Epoch 83/100
804/804 [==============================] - 0s 453us/step - loss: 0.5439 - accuracy: 0.7329
Epoch 84/100
804/804 [==============================] - 0s 436us/step - loss: 0.5427 - accuracy: 0.7341
Epoch 85/100
804/804 [==============================] - 0s 437us/step - loss: 0.5423 - accuracy: 0.7338
Epoch 86/100
804/804 [==============================] - 0s 445us/step - loss: 0.5614 - accuracy: 0.7250
Epoch 87/100
804/804 [==============================] - 0s 435us/step - loss: 0.5462 - accuracy: 0.7316
Epoch 88/100
804/804 [==============================] - 0s 430us/step - loss: 0.5443 - accuracy: 0.7316
Epoch 89/100
804/804 [==============================] - 0s 435us/step - loss: 0.5440 - accuracy: 0.7334
Epoch 90/100
804/804 [==============================] - 0s 444us/step - loss: 0.5442 - accuracy: 0.7350
Epoch 91/100
804/804 [==============================] - 0s 436us/step - loss: 0.5445 - accuracy: 0.7340
Epoch 92/100
804/804 [==============================] - 0s 433us/step - loss: 0.5473 - accuracy: 0.7329
Epoch 93/100
804/804 [==============================] - 0s 471us/step - loss: 0.5498 - accuracy: 0.7327
Epoch 94/100
804/804 [==============================] - 0s 435us/step - loss: 0.5440 - accuracy: 0.7337
Epoch 95/100
804/804 [==============================] - 0s 433us/step - loss: 0.5460 - accuracy: 0.7328
Epoch 96/100
804/804 [==============================] - 0s 432us/step - loss: 0.5435 - accuracy: 0.7346
Epoch 97/100
804/804 [==============================] - 0s 433us/step - loss: 0.5477 - accuracy: 0.7333
Epoch 98/100
804/804 [==============================] - 0s 434us/step - loss: 0.5441 - accuracy: 0.7339
Epoch 99/100
804/804 [==============================] - 0s 433us/step - loss: 0.5432 - accuracy: 0.7341
Epoch 100/100
804/804 [==============================] - 0s 433us/step - loss: 0.5439 - accuracy: 0.7343

In [25]:
# Evaluate the model using the test data (THIRD ATTEMPT)
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5533 - accuracy: 0.7332 - 142ms/epoch - 531us/step
Loss: 0.5532644391059875, Accuracy: 0.7331778407096863

In [27]:
# Export our model to HDF5 file
filepath = r"AlphabetSoupModel_Optimization.h5"
nn.save(filepath, save_format='h5')